name: Run InspectCode on Pull Requests or direct commits on Master

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ "master", "features/resharper-cli" ]
  pull_request:
    branches: [ "master", "features/resharper-cli" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
# This workflow contains a single job called "inspect"
  inspect-goit:  
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2


    - uses: goit/setup-resharper@v1.0.0
      with:
        version: '2020.1'
    - run: ls
      
  #second_job:
  #  needs: inspect-goit
  #  runs-on: ubuntu-latest
  #  steps:
  #    #- run: /resharper-ctl/InspectCode.sh BlazorServerUrlRequestCultureProvider.sln
  #    - run: ls .
