name: "build-test"

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ "master", "features/resharper-cli" ]
  pull_request:
    branches: [ "master", "features/resharper-cli" ]

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set Node.js 12
      uses: actions/setup-node@v1
      with:
        version: 12.x
    - run: npm ci
    - run: npm run build
      
  test:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      #- name: Setup ReSharper CTL
      #  uses: ./
      #  with:
      #    version: 2020.1
      - name: Setup ReSharper Command Line Tools
        uses: goit/setup-resharper@v1.0.0
        with:
          version: 2020.1
      
      - run: InspectCode BlazorServerUrlRequestCultureProvider.sln
